export const SHOW_LOGIN = 'showLogin'
export const HIDDLE_LOGIN = 'hiddleLogin'
export const ADD_USER = 'addUser'

export const SET_CONTENT = 'setContent'
export const SET_CURRENTTIME = 'setCurrentTime'
export const SET_PLAYLISTINFO = 'setPlaylistInfo'
export const SET_PLAYLIST = 'setPlaylist'
export const ADD_TO_PLAYLIST = 'addToPlaylist'
export const RESET_PLAYLIST = 'resetPlaylist'
