export const SET_CONTENT = 'setContent'
export const SET_CURRENTTIME = 'setCurrentTime'
export const ADD_TO_PLAYLIST = 'addToPlayList'
export const RESET_PLAYLIST = 'resetPlayList'
export const RESET_THEMECOLOR = 'resetThemeColor'
